import { League_Spartan } from 'next/font/google';
import Nav from './components/navigation/Nav';
import Footer from './components/Footer';

import './globals.css';

const spartan = League_Spartan({ subsets: ['latin'] });

export const metadata = {
  title: 'Gelato Gelato Pizzaria',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spartan.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
